name: AI Test Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Run Test 1
      run: |
        echo "BOARD
        10,10,1
        11,10,1
        12,10,1
        13,10,1
        DONE" | python ia.py

    - name: Run Test 2
      run: |
        echo "BOARD
        10,10,1
        10,11,1
        10,12,1
        10,13,1
        DONE" | python ia.py

    - name: Run Test 3
      run: |
        echo "BOARD
        10,10,1
        11,11,1
        12,12,1
        13,13,1
        DONE" | python ia.py

    - name: Run Test 4
      run: |
        echo "BOARD
        10,10,2
        11,10,2
        12,10,2
        13,10,2
        DONE" | python ia.py

    - name: Run Test 5
      run: |
        echo "BOARD
        10,10,2
        10,11,2
        10,12,2
        10,13,2
        DONE" | python ia.py

    - name: Run Test 6
      run: |
        echo "BOARD
        10,10,2
        11,11,2
        12,12,2
        13,13,2
        DONE" | python ia.py

    - name: Run Test 7
      run: |
        echo "BOARD
        10,10,1
        11,10,1
        5,5,2
        5,6,2
        5,7,2
        DONE" | python ia.py

    - name: Run Test 8
      run: |
        echo "BOARD
        10,10,2
        10,11,2
        10,13,2
        11,11,1
        11,12,1
        DONE" | python ia.py

    - name: Horizontal attack
      run: |
        echo "BOARD
        8,10,1
        9,10,1
        10,10,1
        11,10,1
        DONE" | python ia.py
    
    - name: Vertical attack
      run: |
        echo "BOARD
        10,8,1
        10,9,1
        10,10,1
        10,11,1
        DONE" | python ia.py

    - name: Diagonal attack (Top Left to Bottom Right)
      run: |
        echo "BOARD
        7,7,1
        8,8,1
        9,9,1
        10,10,1
        DONE" | python ia.py

    - name: Diagonal attack (Bottom Left to Top Right)
      run: |
        echo "BOARD
        10,7,1
        9,8,1
        8,9,1
        7,10,1
        DONE" | python ia.py

    - name: Horizontal near edge attack
      run: |
        echo "BOARD
        0,0,1
        0,1,1
        0,2,1
        0,3,1
        DONE" | python ia.py

    - name: Vertical near edge attack
      run: |
        echo "BOARD
        0,0,1
        1,0,1
        2,0,1
        3,0,1
        DONE" | python ia.py

    - name: Block Horizontal four
      run: |
        echo "BOARD
        8,10,2
        9,10,2
        10,10,2
        11,10,2
        DONE" | python ia.py

    - name: Block Vertical four
      run: |
        echo "BOARD
        10,8,2
        10,9,2
        10,10,2
        10,11,2
        DONE" | python ia.py

    - name: Block Diagonal four (Top Left to Bottom Right)
      run: |
        echo "BOARD
        7,7,2
        8,8,2
        9,9,2
        10,10,2
        DONE" | python ia.py

    - name: Block Diagonal four (Bottom Left to Top Right)
      run: |
        echo "BOARD
        10,7,2
        9,8,2
        8,9,2
        7,10,2
        DONE" | python ia.py
