name: AI Test Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Run Test 1
      run: |
        echo "BOARD
        10,10,1
        11,10,1
        12,10,1
        13,10,1
        DONE" | python ia.py

    - name: Run Test 2
      run: |
        echo "BOARD
        10,10,1
        10,11,1
        10,12,1
        10,13,1
        DONE" | python ia.py

    - name: Run Test 3
      run: |
        echo "BOARD
        10,10,1
        11,11,1
        12,12,1
        13,13,1
        DONE" | python ia.py

    - name: Run Test 4
      run: |
        echo "BOARD
        10,10,2
        11,10,2
        12,10,2
        13,10,2
        DONE" | python ia.py

    - name: Run Test 5
      run: |
        echo "BOARD
        10,10,2
        10,11,2
        10,12,2
        10,13,2
        DONE" | python ia.py

    - name: Run Test 6
      run: |
        echo "BOARD
        10,10,2
        11,11,2
        12,12,2
        13,13,2
        DONE" | python ia.py

    - name: Run Test 7
      run: |
        echo "BOARD
        10,10,1
        11,10,1
        5,5,2
        5,6,2
        5,7,2
        DONE" | python ia.py

    - name: Run Test 8
      run: |
        echo "BOARD
        10,10,2
        10,11,2
        10,13,2
        11,11,1
        11,12,1
        DONE" | python ia.py

    - name: Horizontal attack
      run: |
        echo "BOARD
        8,10,1
        9,10,1
        10,10,1
        11,10,1
        DONE" | python ia.py
    
    - name: Vertical attack
      run: |
        echo "BOARD
        10,8,1
        10,9,1
        10,10,1
        10,11,1
        DONE" | python ia.py

    - name: Diagonal attack (Top Left to Bottom Right)
      run: |
        echo "BOARD
        7,7,1
        8,8,1
        9,9,1
        10,10,1
        DONE" | python ia.py

    - name: Diagonal attack (Bottom Left to Top Right)
      run: |
        echo "BOARD
        10,7,1
        9,8,1
        8,9,1
        7,10,1
        DONE" | python ia.py

    - name: Horizontal near edge attack
      run: |
        echo "BOARD
        0,0,1
        0,1,1
        0,2,1
        0,3,1
        DONE" | python ia.py

    - name: Vertical near edge attack
      run: |
        echo "BOARD
        0,0,1
        1,0,1
        2,0,1
        3,0,1
        DONE" | python ia.py

    - name: Block Horizontal four
      run: |
        echo "BOARD
        8,10,2
        9,10,2
        10,10,2
        11,10,2
        DONE" | python ia.py

    - name: Block Vertical four
      run: |
        echo "BOARD
        10,8,2
        10,9,2
        10,10,2
        10,11,2
        DONE" | python ia.py

    - name: Block Diagonal four (Top Left to Bottom Right)
      run: |
        echo "BOARD
        7,7,2
        8,8,2
        9,9,2
        10,10,2
        DONE" | python ia.py

    - name: Block Diagonal four (Bottom Left to Top Right)
      run: |
        echo "BOARD
        10,7,2
        9,8,2
        8,9,2
        7,10,2
        DONE" | python ia.py

    - name: Horizontal near edge block
      run: |
        echo "BOARD
        0,0,2
        0,1,2
        0,2,2
        0,3,2
        DONE" | python ia.py

    - name: Vertical near edge block
      run: |
        echo "BOARD
        0,0,2
        1,0,2
        2,0,2
        3,0,2
        DONE" | python ia.py

    - name: Block Vertical test
      run: |
        echo "BOARD
        1,0,2
        2,0,2
        3,0,2
        4,0,2
        DONE" | python ia.py
        
    - name: Block Corner Vertical
      run: |
        echo "BOARD
        0,19,2
        1,19,2
        2,19,2
        3,19,2
        DONE" | python ia.py

    - name: Block Corner Vertical Test
      run: |
        echo "BOARD
        1,19,2
        2,19,2
        3,19,2
        4,19,2
        DONE" | python ia.py

    - name: Vertical case 4
      run: |
        echo "BOARD
        7,10,1
        8,10,1
        9,10,1
        11,10,1
        DONE" | python ia.py

    - name: Horizontal case 4
      run: |
        echo "BOARD
        7,10,1
        7,11,1
        7,12,1
        7,14,1
        DONE" | python ia.py

    - name: Diagonal Down-Right Case 4
      run: |
        echo "BOARD
        7,10,1
        8,11,1
        9,12,1
        11,14,1
        DONE" | python ia.py

    - name: Diagonal Up-Right Case 4
      run: |
        echo "BOARD
        11,10,1
        10,11,1
        9,12,1
        7,14,1
        DONE" | python ia.py

    - name: Diagonal Down-Right Case 5
      run: |
        echo "BOARD
        7,10,1
        8,9,1
        9,8,1
        11,6,1
        DONE" | python ia.py

    - name: Diagonal Up-Right Case 5
      run: |
        echo "BOARD
        11,10,1
        10,9,1
        9,8,1
        7,6,1
        DONE" | python ia.py

    - name: Vertical block by the player
      run: |
        echo "BOARD
        10,10,1
        11,10,1
        12,10,1
        13,10,2
        DONE" | python ia.py

    - name: Vertical with a lot of spaces
      run: |
        echo "BOARD
        5,10,1
        
        7,10,1
        
        9,10,1
        10,10,1
        DONE" | python ia.py

    - name: Vertical with one stone
      run: |
        echo "BOARD
        10,10,1
        DONE" | python ia.py

    - name: Horizontal Win and defense
      run: |
        echo "BOARD
        10,10,1
        10,11,1
        10,12,1
        10,13,1
        0,1,2
        0,2,2
        0,3,2
        DONE" | python ia.py

    - name: Vertical Win and defense
      run: |
        echo "BOARD
        10,10,1
        11,10,1
        12,10,1
        13,10,1
        0,1,2
        1,1,2
        2,1,2
        DONE" | python ia.py

    - name: Horizontal attack win with space
      run: |
        echo "BOARD
        10,10,1
        10,11,1
        10,12,1
        10,14,1
        DONE" | python ia.py

    - name: Horizontal attack with space
      run: |
        echo "BOARD
        10,10,1
        10,11,1
        10,13,1
        DONE" | python ia.py

    - name: Vertical attack win with space
      run: |
        echo "BOARD
        10,10,1
        11,10,1
        12,10,1
        14,10,1
        DONE" | python ia.py

    - name: Vertical attack with space
      run: |
        echo "BOARD
        10,10,1
        11,10,1
        13,10,1
        DONE" | python ia.py


    - name: Horizontal defense win with space
      run: |
        echo "BOARD
        10,10,2
        10,11,2
        10,12,2
        10,14,2
        DONE" | python ia.py
  
    - name: Horizontal defense with space
      run: |
        echo "BOARD
        10,10,2
        10,11,2
        10,13,2
        DONE" | python ia.py
  
    - name: Vertical defense win with space
      run: |
        echo "BOARD
        10,10,2
        11,10,2
        12,10,2
        14,10,2
        DONE" | python ia.py
  
    - name: Vertical defense with space
      run: |
        echo "BOARD
        10,10,2
        11,10,2
        13,10,2

        DONE" | python ia.py
